### PR TITLE
Improve french translation

### PR DESCRIPTION
**Pull request by m3-ra**
First of all, thanks for the awesome project, saved us a ton of work in our app! :)
I just made a small change to the french translation to be closer to what a native would say.

### CODE REVIEW

**Comment by hbb20** [comment]
Thank you for this PR. If you have some time can you also make sure all other translations of country name are good?

**Comment by m3-ra** [comment]
Sure, good idea :)
Only made a few very minor changes that I merged with the previous commit.

**Comment by m3-ra** [comment]
Hello :) Any update on a potential merge of this PR?
Thanks a ton!

**Comment by hbb20** [comment]
Oh... If it's an urgent requirement, I can merge in and release a new
version tonight (MDT).

**Comment by hbb20** [comment]
New version 2.3.2 should reflect these changes.

**Pull request merged**
