### PR TITLE
Adds Serbian language support

### PR DESCRIPTION
**Pull request by bozidars27**
This PR adds Serbian language to the list of the supported languages

### CODE REVIEW

**Review by hbb20 — APPROVED** [review]
Thank you. Are these translations verified or are simply google translations?

**Comment by hbb20** [comment]
v.2.6.1 is released with these changes.

**Comment by bozidars27** [comment]
The translations are verified. Serbian is my native language so I translated most of the country names on the spot. For those that I was unsure, I checked on Serbian Wikipedia for the correct official name.

**Comment by hbb20** [comment]
Awesome. Thank you 😊

**Pull request merged**
