### PR TITLE
Danish support

### PR DESCRIPTION
**Pull request by porkyhead**

### CODE REVIEW

**Comment by hbb20** [comment]
@porkyhead , thank you so much for the new language support...

**Comment by porkyhead** [comment]
No problem! I'm from Denmark so I translated most of the countries myself but some of them I didn't know the Danish translation for, so I went with Google Translate.

I am looking forward to have it merged and released as I need it for a client project :)

**Comment by hbb20** [comment]
Try version 2.2.7. 👍

**Comment by porkyhead** [comment]
Thanks a lot :)

And thank you for a very well documented and well done repo!

**Pull request merged**
