### PR TITLE
add country flag

### PR DESCRIPTION
**Pull request by mychaelgo**
PR for #20 

screenshot_20161118-144145

### CODE REVIEW

**Comment by hbb20** [comment]
Great work man... but I also just finished same feature in my own branch...

**Comment by hbb20** [comment]
I appreciate your help and thank you for putting your time for project. When you opened [flag issue](https://github.com/hbb20/CountryCodePickerProject/issues/18), you triggered me to do that today only. I will go ahead with my branch as it has some more fixes as well. Finally thanks man :+1:

**Comment by mychaelgo** [comment]
@hbb20 ok no problem. Are you released the new version?

**Comment by hbb20** [comment]
yeah new version v1.7.1 is released.

**Comment by mychaelgo** [comment]
@hbb20 ok than you 👍

**Pull request closed without merging**
