### PR TITLE
Reduce the size of flags png files

### PR DESCRIPTION
**Pull request by IslamSalah**
Overview:
-
On allocating efforts to reduce our APK size, it was noticed that there is a promising chance to remove some KBs from the .PNG flags files in CCP **without** a noticeable impact on images quality. [Check example flag ](https://user-images.githubusercontent.com/8607770/107499610-73153180-6b95-11eb-8aae-e07b61a0cc9f.gif)

What's the purpose of this PR?
-
aar size optimization 

What's the impact of this PR?
-
Reduce the .PNG flags files size by 44% from 307 KB to 173 KB

### CODE REVIEW

**Comment by IslamSalah** [comment]
CC @hbb20

**Comment by IslamSalah** [comment]
#397

**Comment by IslamSalah** [comment]
@hbb20 I wonder if the repo is active and receiving contributions

**Comment by hbb20** [comment]
Thank you for the contribution🙂 And sorry for late action😞

**Comment by IslamSalah** [comment]
@hbb20 Thank you for the reply, should we expect a new release soon?

**Comment by hbb20** [comment]
Yes👍🏼

**Comment by hbb20** [comment]
Try 2.4.7

**Comment by IslamSalah** [comment]
Working and on comparing it with an app build using CCP v2.4.6, ~134 KB were removed as mentioned in the PR description
Screenshot 2021-02-22 at 9 28 26 pm

**Pull request merged**
