### PR TITLE
Bump libphonenumber-android version

### PR DESCRIPTION
**Pull request by sp0rk**
Updates countries metadata. Most notably Cote d'Ivoire broken validation starting 2021-01-31 -  #464

### CODE REVIEW

**Comment by hbb20** [comment]
Thanks for the PR🙂

**Comment by julian-jurec-novoda** [comment]
@hbb20 When can we expect the release of a new version containing this update? It's quite crucial to many use-cases as it fixes broken validation :)

**Comment by hbb20** [comment]
I understand. Can I do it after office today?

**Comment by julian-jurec-novoda** [comment]
Sure, I'd appreciate it :). Thanks for quick response and the library itself. Great stuff.

**Comment by hbb20** [comment]
Hey. I released new version. Try by bumping up ccp version number to 2.4.6. 👍🏼

**Pull request merged**
