### PR TITLE
Support Khmer Language

### PR DESCRIPTION
**Pull request by PutheaMam**
added KHMER("km") to support Khmer language

### CODE REVIEW

**Comment by PutheaMam** [comment]
I'm from Cambodia. I have made some changes to the library so it could support my language

**Comment by hbb20** [comment]
I believe you have already added this file in your local machine you might wanna track and commit with Git and push..

**Comment by popnitesh** [comment]
how to display only flag or country code  selected time and set time ?

**Comment by hbb20** [comment]
If phone number is not your use case you can use Android Country Picker
which comes with this flexibility.
https://github.com/hbb20/AndroidCountryPicker


Although neither this nor Android Country Picker have data about time zone
(in case you are looking for that)

**Comment by hbb20** [comment]
Feel free to reopen when translation files are added

**Pull request closed without merging**
