### PR TITLE
Support national number formatting

### PR DESCRIPTION
**Pull request by JoshuaBradbury**
Added support for formatting national numbers as well as an option to disable it (disabled by default). The only bit left is to figure out the best way to display it in the example number, and update the example app to mention it. 

see #287

### CODE REVIEW

**Comment by hbb20** [comment]
Thank you for the PR 👍

**Comment by hbb20** [comment]
I truly appreciate this PR. Right now I am running little busy, so I will try my best to review and merge this in ASAP.

**Comment by hbb20** [comment]
Can you please post the sample country code and phone number that you used for valid testing?

**Comment by JoshuaBradbury** [comment]
I tried random numbers, with and without a leading 0 and made sure it formatted them the same.

**Pull request merged**
