### PR TITLE
update pakistan flag

### LINKED ISSUE #570: Wrong color for Pakistan Flag
The Pakistan flag is a lighter green than it should be:

Screenshot_20230113_183022_Flashat (Preprod)

When it should be infact this: 

Pak Flag

### PR DESCRIPTION
**Pull request by shahimclt**
Fixes #570 
replaced the flag of pakistan with the correct one

### CODE REVIEW

**Comment by shahimclt** [comment]
Hi @hbb20 is it possible to merge this PR. This was reported by a client of mine and would love to get it fixed. Otherwise I might have to fork the project for the time being

**Comment by hbb20** [comment]
Can it wait until Sunday? I can take a look at it in the weekend.

**Comment by shahimclt** [comment]
No issues. I have a couple weeks time. Thanks again.

**Comment by hbb20** [comment]
Just released 2.7.0. Should be available for download soon.

**Pull request merged**
