### PR TITLE
Greek Language Added to hbb20 Country Picker Project

### PR DESCRIPTION
**Pull request by khanboy1989**

### CODE REVIEW

**Comment by khanboy1989** [comment]
Happy codind and my new very first pull request

**Comment by hbb20** [comment]
@khanboy1989 , Congratulations on your very first PR. Code changes looks good. I will merge after a test by running code.

Just want to know if the translations are done manually and can be considered as authenticate or they are from some translation service (like google translator) and might need correction in future?

**Comment by khanboy1989** [comment]
Hi Harsh,

To be honest, greek.xml is completed by me. Some of the countries I did not
know so I checked them on google but I tried to avoid using Google
Translate. However, I have used google translate in some countries i can
say a few times not a lot

Regards
Serhan Khan

**Comment by niktses** [comment]
Hello am also interested in using greek so is there any updates on when the merge will take place?

**Comment by niktses** [comment]
any updates?

**Comment by khanboy1989** [comment]
Waiting for Harsh to merge my pull request. He did not reply back or merge my changes

**Comment by hbb20** [comment]
Sorry everyone. I was all set to release but something was broken in my
tool so could not upload. Then got stuck with finals and projects. I'll try
to fix it as soon as possible. Sorry for the long delay.

**Comment by hbb20** [comment]
Until we release official v2.2.4, please check v2.2.3.1. It has greek language support. If you face any problem, please let us know...

**Comment by khanboy1989** [comment]
Thanks for the merge

**Comment by niktses** [comment]
Thanks a lot

**Pull request merged**
