### PR TITLE
Optimize all resources with imageoptim removing 64.8% in library size

### PR DESCRIPTION
**Pull request by danielgomezrico**
I applied multiple lose-less compressionz algorithms with [imageoptim](https://imageoptim.com/mac) on each resource of the project, including each flag and got:

> Saved 828 KB out of 1,4 MB. 64,8 % per file on average (up to 95,9 %)

So this will make no visual changes but will improve the library.

### CODE REVIEW

**Comment by IslamSalah** [comment]
> Saved 828 KB out of 1,4 MB.

Hi @danielgomezrico, curious how you calculated this "828 KB" ?
As comparing APK size [before](https://github.com/hbb20/CountryCodePickerProject/commit/e14c8a1d7d1bef975957b5949f4c3bf630cfc2b6)/[after](https://github.com/hbb20/CountryCodePickerProject/commit/d55449e0379758e57b7de579f396c3631131e262) this PR, using the apk analyzer, the diff was 616 KB

compare apks

**Comment by IslamSalah** [comment]
cc @hbb20

**Comment by danielgomezrico** [comment]
@IslamSalah the tool [imageoptim](https://imageoptim.com/mac) prints that at the end of the process

**Comment by IslamSalah** [comment]
@danielgomezrico Thank you for the quick reply. Seems like it included improvement both in `app` & `ccp` modules. wdyt?
however library users will be only concerned only about the later

**Comment by danielgomezrico** [comment]
@IslamSalah sorry, I dont get your question, can you please reword it?

**Comment by IslamSalah** [comment]
> Saved 828 KB out of 1,4 MB

616 KB removed fom `ccp`
212 KB removed from `app`
@danielgomezrico

**Pull request merged**
