### PR TITLE
Kazakh language support

### PR DESCRIPTION
**Pull request by janbolat**
Hello!
Please add a Kazakh language support as we need it in our project.
Thank you.

### CODE REVIEW

**Comment by hbb20** [comment]
Sorry for delayed response.. Please try v2.3.3.

**Comment by janbolat** [comment]
@hbb20 Thank you. But v2.3.3 is still not available

**Comment by hbb20** [comment]
I just checked and it working for me...
On my testing app, I was able to pull v2.3.3
image

And set KAZAKH as my default language
image

and it runs well:
image

**Comment by janbolat** [comment]
Thank you, it is available now.

**Pull request merged**
