### PR TITLE
Urdu Language support Added

### PR DESCRIPTION
**Pull request by hamzaahmedkhan**

### CODE REVIEW

**Comment by hbb20** [comment]
Thank you for the Urdu support. Just wanted to ask if these translations are manual and verified or they are just translated using some translator tool like Google translator?

**Comment by hamzaahmedkhan** [comment]
Hi,
Popular countries names are manual and verified, but few countries names (like small islands) are translated by Google but I again checked them that it is the right translation.
Urdu is my mother language that's why I wanted to contribute.
Sent from Yahoo Mail on Android 
 
  On Mon, Sep 16, 2019 at 23:37, Harsh B. Bhakta<notifications@github.com> wrote:   
Thank you for the Urdu support. Just wanted to ask if these translations are manual and verified or they are just translated using some translator tool like Google translator?

**Comment by hbb20** [comment]
Thank you. We truly appreciate your contribution. Is it OK if we contact you if more Urdu translations verifications are required when new country is added?

**Comment by hamzaahmedkhan** [comment]
Sure I am up and available.

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 17, 2019 at 18:45, Harsh B. Bhakta<notifications@github.com> wrote:   
Thank you. We truly appreciate your contribution. Is it OK if we contact you if more Urdu translations verifications are required when new country is added?

**Pull request merged**
