### PR TITLE
Removed additional stripes above and below US flag.

### LINKED ISSUE #393: Additional stripes above and below US flag when`ccp_flagBorderColor` used.
There are additional stripes above and below US flag when non-transparent `ccp_flagBorderColor` used.

See image below:
image

### PR DESCRIPTION
**Pull request by rafalswierkot**
This fixes #393. Redundant stripes above and below the flag becomes visible when non transparent `ccp_flagBorderColor` property is defined.

This commit just removes the redundant stripes from US flag image.

### CODE REVIEW

**Comment by krokers** [comment]
@hbb20 Any update on that? We use the library in our project, and unfortunately the US flag is broken with border is used. 
Can we merge this fix?

**Comment by hbb20** [comment]
Is it OK if I do it this evening?

**Comment by krokers** [comment]
That would be perfect!

czw., 7 maj 2020, 16:53 użytkownik Harsh B. Bhakta <notifications@github.com>
napisał:

**Comment by hbb20** [comment]
I just published new version with this PR fixes. Sorry for delay. Please try v2.3.9

**Comment by krokers** [comment]
Works like a charm! Thanks!

pt., 8 maj 2020 o 16:27 Harsh B. Bhakta <notifications@github.com>
napisał(a):

**Pull request merged**
