### PR TITLE
Extract the changelog in a CHANGELOG.md file

### PR DESCRIPTION
**Pull request by Ajojo44**
Extract the changelog in a CHANGELOG file to follow Git repository best practices.

Here is a nice tutorial exploring how to improve Changelogs: https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

**Comment by JoshuaBradbury** [comment]
Do we also want to update the changelong to match the standard of keep a changelog, or should it be a separate PR?

**Comment by hbb20** [comment]
@Ajojo44 thanks for this... @JoshuaBradbury, can you please elaborate what do you mean by "standard of keep a changelog"?

**Comment by hbb20** [comment]
do you means adding specified sections in the article? I will welcome a PR or update in this PR otherwise I will take care of adding new version entries with specified standard... 👍

**Comment by JoshuaBradbury** [comment]
Yes the specific sections they mention. If @Ajojo44 wants to do this that's cool if not yeah I would be happy to.

**Pull request merged**
